local ServerScriptService = game:GetService("ServerScriptService")
local CloseRangeWeapon = require(ServerScriptService.Server.Weapons.CloseRangeWeapon)

return {
	{
		Name = "Sword",
		Price = 100,
	},
	{
		Name = "Slap Hand",
		Price = 300,
	},
	{
		Name = "Ban Hammer",
		Price = 1000,
	},
	{
		Name = "Fire Brand",
		Price = 20000,
	},
	{
		Name = "Sling Shot",
		Price = 1000,
	},
	{
		Name = "Paintball Gun",
		Price = 5000,
	},
	{
		Name = "Rocket Launcher",
		Price = 20000,
	},
}
